import { WorkflowState, NodeStatus } from '../types';

/** @preset-id preset-9shot-healing-video */
/** 9分镜治愈动画：文本生成分镜脚本 → 9镜画面链式生图(9:16) + 9镜图生视频 */
const workflow: WorkflowState = {
  id: 'preset-9shot-healing-video',
  name: '9分镜治愈动画',
  updatedAt: Date.now(),
  isDirty: false,
  isRunning: false,
  globalInputs: {},
  connections: [
    { id: 'h9-c-story-script', source_node_id: 'node-story', source_port_id: 'out-text', target_node_id: 'node-script', target_port_id: 'in-text' },
    { id: 'h9-c-img1-img2', source_node_id: 'node-img1', source_port_id: 'out-image', target_node_id: 'node-img2', target_port_id: 'in-image' },
    { id: 'h9-c-img2-img3', source_node_id: 'node-img2', source_port_id: 'out-image', target_node_id: 'node-img3', target_port_id: 'in-image' },
    { id: 'h9-c-img3-img4', source_node_id: 'node-img3', source_port_id: 'out-image', target_node_id: 'node-img4', target_port_id: 'in-image' },
    { id: 'h9-c-img4-img5', source_node_id: 'node-img4', source_port_id: 'out-image', target_node_id: 'node-img5', target_port_id: 'in-image' },
    { id: 'h9-c-img5-img6', source_node_id: 'node-img5', source_port_id: 'out-image', target_node_id: 'node-img6', target_port_id: 'in-image' },
    { id: 'h9-c-img6-img7', source_node_id: 'node-img6', source_port_id: 'out-image', target_node_id: 'node-img7', target_port_id: 'in-image' },
    { id: 'h9-c-img7-img8', source_node_id: 'node-img7', source_port_id: 'out-image', target_node_id: 'node-img8', target_port_id: 'in-image' },
    { id: 'h9-c-img8-img9', source_node_id: 'node-img8', source_port_id: 'out-image', target_node_id: 'node-img9', target_port_id: 'in-image' },
    { id: 'h9-c-p1-img1', source_node_id: 'node-script', source_port_id: 'image-1-prompt', target_node_id: 'node-img1', target_port_id: 'in-text' },
    { id: 'h9-c-p2-img2', source_node_id: 'node-script', source_port_id: 'image-2-prompt', target_node_id: 'node-img2', target_port_id: 'in-text' },
    { id: 'h9-c-p3-img3', source_node_id: 'node-script', source_port_id: 'image-3-prompt', target_node_id: 'node-img3', target_port_id: 'in-text' },
    { id: 'h9-c-p4-img4', source_node_id: 'node-script', source_port_id: 'image-4-prompt', target_node_id: 'node-img4', target_port_id: 'in-text' },
    { id: 'h9-c-p5-img5', source_node_id: 'node-script', source_port_id: 'image-5-prompt', target_node_id: 'node-img5', target_port_id: 'in-text' },
    { id: 'h9-c-p6-img6', source_node_id: 'node-script', source_port_id: 'image-6-prompt', target_node_id: 'node-img6', target_port_id: 'in-text' },
    { id: 'h9-c-p7-img7', source_node_id: 'node-script', source_port_id: 'image-7-prompt', target_node_id: 'node-img7', target_port_id: 'in-text' },
    { id: 'h9-c-p8-img8', source_node_id: 'node-script', source_port_id: 'image-8-prompt', target_node_id: 'node-img8', target_port_id: 'in-text' },
    { id: 'h9-c-p9-img9', source_node_id: 'node-script', source_port_id: 'image-9-prompt', target_node_id: 'node-img9', target_port_id: 'in-text' },
    { id: 'h9-c-img1-vid1', source_node_id: 'node-img1', source_port_id: 'out-image', target_node_id: 'node-vid1', target_port_id: 'in-image' },
    { id: 'h9-c-m1-vid1', source_node_id: 'node-script', source_port_id: 'video-1-prompt', target_node_id: 'node-vid1', target_port_id: 'in-text' },
    { id: 'h9-c-img2-vid2', source_node_id: 'node-img2', source_port_id: 'out-image', target_node_id: 'node-vid2', target_port_id: 'in-image' },
    { id: 'h9-c-m2-vid2', source_node_id: 'node-script', source_port_id: 'video-2-prompt', target_node_id: 'node-vid2', target_port_id: 'in-text' },
    { id: 'h9-c-img3-vid3', source_node_id: 'node-img3', source_port_id: 'out-image', target_node_id: 'node-vid3', target_port_id: 'in-image' },
    { id: 'h9-c-m3-vid3', source_node_id: 'node-script', source_port_id: 'video-3-prompt', target_node_id: 'node-vid3', target_port_id: 'in-text' },
    { id: 'h9-c-img4-vid4', source_node_id: 'node-img4', source_port_id: 'out-image', target_node_id: 'node-vid4', target_port_id: 'in-image' },
    { id: 'h9-c-m4-vid4', source_node_id: 'node-script', source_port_id: 'video-4-prompt', target_node_id: 'node-vid4', target_port_id: 'in-text' },
    { id: 'h9-c-img5-vid5', source_node_id: 'node-img5', source_port_id: 'out-image', target_node_id: 'node-vid5', target_port_id: 'in-image' },
    { id: 'h9-c-m5-vid5', source_node_id: 'node-script', source_port_id: 'video-5-prompt', target_node_id: 'node-vid5', target_port_id: 'in-text' },
    { id: 'h9-c-img6-vid6', source_node_id: 'node-img6', source_port_id: 'out-image', target_node_id: 'node-vid6', target_port_id: 'in-image' },
    { id: 'h9-c-m6-vid6', source_node_id: 'node-script', source_port_id: 'video-6-prompt', target_node_id: 'node-vid6', target_port_id: 'in-text' },
    { id: 'h9-c-img7-vid7', source_node_id: 'node-img7', source_port_id: 'out-image', target_node_id: 'node-vid7', target_port_id: 'in-image' },
    { id: 'h9-c-m7-vid7', source_node_id: 'node-script', source_port_id: 'video-7-prompt', target_node_id: 'node-vid7', target_port_id: 'in-text' },
    { id: 'h9-c-img8-vid8', source_node_id: 'node-img8', source_port_id: 'out-image', target_node_id: 'node-vid8', target_port_id: 'in-image' },
    { id: 'h9-c-m8-vid8', source_node_id: 'node-script', source_port_id: 'video-8-prompt', target_node_id: 'node-vid8', target_port_id: 'in-text' },
    { id: 'h9-c-img9-vid9', source_node_id: 'node-img9', source_port_id: 'out-image', target_node_id: 'node-vid9', target_port_id: 'in-image' },
    { id: 'h9-c-m9-vid9', source_node_id: 'node-script', source_port_id: 'video-9-prompt', target_node_id: 'node-vid9', target_port_id: 'in-text' }
  ],
  nodes: [
    { id: 'node-story', tool_id: 'text-input', x: -360, y: 360, status: NodeStatus.IDLE, data: { value: '蓝天白云，田野乡村，治愈系动画脚本' } },
    {
      id: 'node-script',
      tool_id: 'text-generation',
      x: 80,
      y: 200,
      data: {
        model: 'doubao-seed-1-6-vision-250815',
        mode: 'custom',
        customInstruction:`请生成一个9分镜治愈动画的分镜脚本，保持9镜风格统一，竖屏构图，输出18个字段：
        - image-1-prompt ~ image-9-prompt 描述该镜的静态画面（治愈、柔和、自然风格）；
        - video-1-prompt ~ video-9-prompt 描述该镜的镜头运动或画面内动作。`,
        custom_outputs: [
          { id: 'image-1-prompt', label: '第1镜静态画面提示词', description: '第1镜静态画面提示词' },
          { id: 'video-1-prompt', label: '第1镜运镜提示词', description: '第1镜运镜提示词' },
          { id: 'image-2-prompt', label: '第2镜静态画面提示词', description: '第2镜静态画面提示词' },
          { id: 'video-2-prompt', label: '第2镜运镜提示词', description: '第2镜运镜提示词' },
          { id: 'image-3-prompt', label: '第3镜静态画面提示词', description: '第3镜静态画面提示词' },
          { id: 'video-3-prompt', label: '第3镜运镜提示词', description: '第3镜运镜提示词' },
          { id: 'image-4-prompt', label: '第4镜静态画面提示词', description: '第4镜静态画面提示词' },
          { id: 'video-4-prompt', label: '第4镜运镜提示词', description: '第4镜运镜提示词' },
          { id: 'image-5-prompt', label: '第5镜静态画面提示词', description: '第5镜静态画面提示词' },
          { id: 'video-5-prompt', label: '第5镜运镜提示词', description: '第5镜运镜提示词' },
          { id: 'image-6-prompt', label: '第6镜静态画面提示词', description: '第6镜静态画面提示词' },
          { id: 'video-6-prompt', label: '第6镜运镜提示词', description: '第6镜运镜提示词' },
          { id: 'image-7-prompt', label: '第7镜静态画面提示词', description: '第7镜静态画面提示词' },
          { id: 'video-7-prompt', label: '第7镜运镜提示词', description: '第7镜运镜提示词' },
          { id: 'image-8-prompt', label: '第8镜静态画面提示词', description: '第8镜静态画面提示词' },
          { id: 'video-8-prompt', label: '第8镜运镜提示词', description: '第8镜运镜提示词' },
          { id: 'image-9-prompt', label: '第9镜静态画面提示词', description: '第9镜静态画面提示词' },
          { id: 'video-9-prompt', label: '第9镜运镜提示词', description: '第9镜运镜提示词' },
        ]
      },
      status: NodeStatus.IDLE
    },
    { id: 'node-img1', tool_id: 'text-to-image', x: 520, y: 380, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img2', tool_id: 'image-to-image', x: 520, y: 452, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img3', tool_id: 'image-to-image', x: 520, y: 524, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img4', tool_id: 'image-to-image', x: 520, y: 596, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img5', tool_id: 'image-to-image', x: 520, y: 668, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img6', tool_id: 'image-to-image', x: 520, y: 740, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img7', tool_id: 'image-to-image', x: 520, y: 812, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img8', tool_id: 'image-to-image', x: 520, y: 884, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img9', tool_id: 'image-to-image', x: 520, y: 956, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-vid1', tool_id: 'video-gen-image', x: 880, y: 380, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid2', tool_id: 'video-gen-image', x: 880, y: 452, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid3', tool_id: 'video-gen-image', x: 880, y: 524, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid4', tool_id: 'video-gen-image', x: 880, y: 596, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid5', tool_id: 'video-gen-image', x: 880, y: 668, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid6', tool_id: 'video-gen-image', x: 880, y: 740, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid7', tool_id: 'video-gen-image', x: 880, y: 812, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid8', tool_id: 'video-gen-image', x: 880, y: 884, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid9', tool_id: 'video-gen-image', x: 880, y: 956, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } }
  ]
};

export default workflow;
