import { WorkflowState, NodeStatus } from '../types';

/** @preset-id preset-9shot-healing-video */
/** 9分镜治愈动画：文本生成分镜脚本 → 9镜画面链式生图(9:16) + 9镜图生视频 */
const workflow: WorkflowState = {
  id: 'preset-9shot-healing-video',
  name: '9分镜治愈动画',
  updatedAt: Date.now(),
  isDirty: false,
  isRunning: false,
  globalInputs: {},
  connections: [
    { id: 'h9-c-p1-img1', source_node_id: 'node-p1', source_port_id: 'out-text', target_node_id: 'node-img1', target_port_id: 'in-text' },
    { id: 'h9-c-img1-img2', source_node_id: 'node-img1', source_port_id: 'out-image', target_node_id: 'node-img2', target_port_id: 'in-image' },
    { id: 'h9-c-img2-img3', source_node_id: 'node-img2', source_port_id: 'out-image', target_node_id: 'node-img3', target_port_id: 'in-image' },
    { id: 'h9-c-img3-img4', source_node_id: 'node-img3', source_port_id: 'out-image', target_node_id: 'node-img4', target_port_id: 'in-image' },
    { id: 'h9-c-img4-img5', source_node_id: 'node-img4', source_port_id: 'out-image', target_node_id: 'node-img5', target_port_id: 'in-image' },
    { id: 'h9-c-img5-img6', source_node_id: 'node-img5', source_port_id: 'out-image', target_node_id: 'node-img6', target_port_id: 'in-image' },
    { id: 'h9-c-img6-img7', source_node_id: 'node-img6', source_port_id: 'out-image', target_node_id: 'node-img7', target_port_id: 'in-image' },
    { id: 'h9-c-img7-img8', source_node_id: 'node-img7', source_port_id: 'out-image', target_node_id: 'node-img8', target_port_id: 'in-image' },
    { id: 'h9-c-img8-img9', source_node_id: 'node-img8', source_port_id: 'out-image', target_node_id: 'node-img9', target_port_id: 'in-image' },
    { id: 'h9-c-p2-img2', source_node_id: 'node-p2', source_port_id: 'out-text', target_node_id: 'node-img2', target_port_id: 'in-text' },
    { id: 'h9-c-p3-img3', source_node_id: 'node-p3', source_port_id: 'out-text', target_node_id: 'node-img3', target_port_id: 'in-text' },
    { id: 'h9-c-p4-img4', source_node_id: 'node-p4', source_port_id: 'out-text', target_node_id: 'node-img4', target_port_id: 'in-text' },
    { id: 'h9-c-p5-img5', source_node_id: 'node-p5', source_port_id: 'out-text', target_node_id: 'node-img5', target_port_id: 'in-text' },
    { id: 'h9-c-p6-img6', source_node_id: 'node-p6', source_port_id: 'out-text', target_node_id: 'node-img6', target_port_id: 'in-text' },
    { id: 'h9-c-p7-img7', source_node_id: 'node-p7', source_port_id: 'out-text', target_node_id: 'node-img7', target_port_id: 'in-text' },
    { id: 'h9-c-p8-img8', source_node_id: 'node-p8', source_port_id: 'out-text', target_node_id: 'node-img8', target_port_id: 'in-text' },
    { id: 'h9-c-p9-img9', source_node_id: 'node-p9', source_port_id: 'out-text', target_node_id: 'node-img9', target_port_id: 'in-text' },
    { id: 'h9-c-img1-vid1', source_node_id: 'node-img1', source_port_id: 'out-image', target_node_id: 'node-vid1', target_port_id: 'in-image' },
    { id: 'h9-c-m1-vid1', source_node_id: 'node-m1', source_port_id: 'out-text', target_node_id: 'node-vid1', target_port_id: 'in-text' },
    { id: 'h9-c-img2-vid2', source_node_id: 'node-img2', source_port_id: 'out-image', target_node_id: 'node-vid2', target_port_id: 'in-image' },
    { id: 'h9-c-m2-vid2', source_node_id: 'node-m2', source_port_id: 'out-text', target_node_id: 'node-vid2', target_port_id: 'in-text' },
    { id: 'h9-c-img3-vid3', source_node_id: 'node-img3', source_port_id: 'out-image', target_node_id: 'node-vid3', target_port_id: 'in-image' },
    { id: 'h9-c-m3-vid3', source_node_id: 'node-m3', source_port_id: 'out-text', target_node_id: 'node-vid3', target_port_id: 'in-text' },
    { id: 'h9-c-img4-vid4', source_node_id: 'node-img4', source_port_id: 'out-image', target_node_id: 'node-vid4', target_port_id: 'in-image' },
    { id: 'h9-c-m4-vid4', source_node_id: 'node-m4', source_port_id: 'out-text', target_node_id: 'node-vid4', target_port_id: 'in-text' },
    { id: 'h9-c-img5-vid5', source_node_id: 'node-img5', source_port_id: 'out-image', target_node_id: 'node-vid5', target_port_id: 'in-image' },
    { id: 'h9-c-m5-vid5', source_node_id: 'node-m5', source_port_id: 'out-text', target_node_id: 'node-vid5', target_port_id: 'in-text' },
    { id: 'h9-c-img6-vid6', source_node_id: 'node-img6', source_port_id: 'out-image', target_node_id: 'node-vid6', target_port_id: 'in-image' },
    { id: 'h9-c-m6-vid6', source_node_id: 'node-m6', source_port_id: 'out-text', target_node_id: 'node-vid6', target_port_id: 'in-text' },
    { id: 'h9-c-img7-vid7', source_node_id: 'node-img7', source_port_id: 'out-image', target_node_id: 'node-vid7', target_port_id: 'in-image' },
    { id: 'h9-c-m7-vid7', source_node_id: 'node-m7', source_port_id: 'out-text', target_node_id: 'node-vid7', target_port_id: 'in-text' },
    { id: 'h9-c-img8-vid8', source_node_id: 'node-img8', source_port_id: 'out-image', target_node_id: 'node-vid8', target_port_id: 'in-image' },
    { id: 'h9-c-m8-vid8', source_node_id: 'node-m8', source_port_id: 'out-text', target_node_id: 'node-vid8', target_port_id: 'in-text' },
    { id: 'h9-c-img9-vid9', source_node_id: 'node-img9', source_port_id: 'out-image', target_node_id: 'node-vid9', target_port_id: 'in-image' },
    { id: 'h9-c-m9-vid9', source_node_id: 'node-m9', source_port_id: 'out-text', target_node_id: 'node-vid9', target_port_id: 'in-text' }
  ],
  nodes: [
    {
      id: 'node-script',
      tool_id: 'text-generation',
      x: 80,
      y: 200,
      data: {
        value: '请生成一个9分镜治愈动画的分镜脚本。每镜输出两行：第一行「画面」描述该镜的静态画面（治愈、柔和、自然风格），第二行「运镜」描述该镜的镜头运动或画面内动作。保持9镜风格统一，竖屏构图。',
        model: 'deepseek-v3-2-251201',
        mode: 'basic',
        custom_outputs: [{ id: 'out-text', label: '分镜脚本', description: '9镜画面与运镜提示词' }]
      },
      status: NodeStatus.IDLE
    },
    { id: 'node-p1', tool_id: 'text-input', x: 80, y: 380, status: NodeStatus.IDLE, data: { value: '第1镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p2', tool_id: 'text-input', x: 80, y: 452, status: NodeStatus.IDLE, data: { value: '第2镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p3', tool_id: 'text-input', x: 80, y: 524, status: NodeStatus.IDLE, data: { value: '第3镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p4', tool_id: 'text-input', x: 80, y: 596, status: NodeStatus.IDLE, data: { value: '第4镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p5', tool_id: 'text-input', x: 80, y: 668, status: NodeStatus.IDLE, data: { value: '第5镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p6', tool_id: 'text-input', x: 80, y: 740, status: NodeStatus.IDLE, data: { value: '第6镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p7', tool_id: 'text-input', x: 80, y: 812, status: NodeStatus.IDLE, data: { value: '第7镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p8', tool_id: 'text-input', x: 80, y: 884, status: NodeStatus.IDLE, data: { value: '第8镜画面（从上方分镜脚本复制）' } },
    { id: 'node-p9', tool_id: 'text-input', x: 80, y: 956, status: NodeStatus.IDLE, data: { value: '第9镜画面（从上方分镜脚本复制）' } },
    { id: 'node-m1', tool_id: 'text-input', x: 280, y: 380, status: NodeStatus.IDLE, data: { value: '第1镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m2', tool_id: 'text-input', x: 280, y: 452, status: NodeStatus.IDLE, data: { value: '第2镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m3', tool_id: 'text-input', x: 280, y: 524, status: NodeStatus.IDLE, data: { value: '第3镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m4', tool_id: 'text-input', x: 280, y: 596, status: NodeStatus.IDLE, data: { value: '第4镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m5', tool_id: 'text-input', x: 280, y: 668, status: NodeStatus.IDLE, data: { value: '第5镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m6', tool_id: 'text-input', x: 280, y: 740, status: NodeStatus.IDLE, data: { value: '第6镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m7', tool_id: 'text-input', x: 280, y: 812, status: NodeStatus.IDLE, data: { value: '第7镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m8', tool_id: 'text-input', x: 280, y: 884, status: NodeStatus.IDLE, data: { value: '第8镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-m9', tool_id: 'text-input', x: 280, y: 956, status: NodeStatus.IDLE, data: { value: '第9镜运镜（从上方分镜脚本复制）' } },
    { id: 'node-img1', tool_id: 'text-to-image', x: 520, y: 380, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img2', tool_id: 'image-to-image', x: 520, y: 452, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img3', tool_id: 'image-to-image', x: 520, y: 524, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img4', tool_id: 'image-to-image', x: 520, y: 596, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img5', tool_id: 'image-to-image', x: 520, y: 668, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img6', tool_id: 'image-to-image', x: 520, y: 740, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img7', tool_id: 'image-to-image', x: 520, y: 812, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img8', tool_id: 'image-to-image', x: 520, y: 884, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-img9', tool_id: 'image-to-image', x: 520, y: 956, status: NodeStatus.IDLE, data: { value: '', model: 'Qwen-Image-2512', aspectRatio: '9:16' } },
    { id: 'node-vid1', tool_id: 'video-gen-image', x: 880, y: 380, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid2', tool_id: 'video-gen-image', x: 880, y: 452, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid3', tool_id: 'video-gen-image', x: 880, y: 524, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid4', tool_id: 'video-gen-image', x: 880, y: 596, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid5', tool_id: 'video-gen-image', x: 880, y: 668, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid6', tool_id: 'video-gen-image', x: 880, y: 740, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid7', tool_id: 'video-gen-image', x: 880, y: 812, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid8', tool_id: 'video-gen-image', x: 880, y: 884, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } },
    { id: 'node-vid9', tool_id: 'video-gen-image', x: 880, y: 956, status: NodeStatus.IDLE, data: { value: '', model: 'Wan2.2_I2V_A14B_distilled', aspectRatio: '9:16' } }
  ]
};

export default workflow;
